### ISSUE TITLE
Warning prints on the defineBinaries functions

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-ccp4#4]
@rmarabini , @mmmtnez Could you consider to remove the following warning prints from the "defineBinaries" function?
https://github.com/scipion-em/scipion-em-ccp4/blob/devel/ccp4/__init__.py#L157

I'm not against highlighting the error, but I think this function is not the place. @pconesa where should fit best. I think that we should allow the plugins to be installed (and work until some extend) even if the underlying binaries are not. I find this print a bit disruptive of you have all plugins activated, but not all binaries.

**Comment by rmarabini** [comment]
Hi @delarosatrevin , @pconesa , @mmmtnez , 

 I'm not against moving the error to other place providing somebody tell me where ;-). This plugin is totally useless without the binaries so the protocols should not appears in Scipion menu if the binaries are not installed. (the same happens with phenix)

**Comment by delarosatrevin** [comment]
Of course, for real processing, the plugin is useless without the binaries...but even if the plugin is installed and the binaries are not...I would prefer not to have that annoying message. I think it is useful to have all plugins installed, so we can do many automatic checks (imports, protocols, etc) on the code...without executing the protocols.

**Comment by pconesa** [comment]
Scipion uses a base method to check if the installation is "valid": Here https://github.com/I2PC/scipion/blob/devel-pluginization/pyworkflow/protocol/protocol.py#L1623

This relays on a "generic" validateInstallation method that resides on the Plugin.validateInstallation:
https://github.com/I2PC/scipion/blob/devel-pluginization/pyworkflow/plugin.py#L273

All this is a generic implementation, and will work, in most cases where, variables are paths like 'RELION_HOME = /home/xxx/em/relion-2.1'

I think, this is not the case for CCP4 and others in that case you can:

A: Overwrite/implement CPP4.Plugin.validateInstallation():

And do whatever checks you are doing now but inside it. This will be shared by any protocol of that plugin

B: If you need a more fine tuned validation then, you can overwrite some/all protocol.validateInstallation methods accordingly.

**Comment by pconesa** [comment]
Additionally, if the validateInstallation is properly wired up.....a message will be shown upon protocol execution, plus the icon in the "protcols tree" will appear grey if "not installed".

**Comment by delarosatrevin** [comment]
Thanks @pconesa. I think this should be the place where this warning should go.

**Comment by rmarabini** [comment]
@pconesa  I am lost here. What I see is that each protocol redefines    validateInstallation and the redefinition
calls checkBinaries. Is this wrong? why? I simply do not understand how the checking  is done.

**Comment by pconesa** [comment]
After a quick look, I do not see a reason for annoying prints. Let me install it and see

**Comment by pconesa** [comment]
As it is now I think it works fine and I do not see any print lines. Maybe it is fixed?
![image](https://user-images.githubusercontent.com/785633/93496856-08c2d280-f910-11ea-981c-cc1305454e50.png)

**Comment by pconesa** [comment]
De define binaries does not have any print lines. I think this is solved.

**Comment by pconesa** [comment]
Turns out I'd fixed it: https://github.com/scipion-em/scipion-em-ccp4/commit/18c0170fccb0aa6ed16cb5c3957791c0bd02d8c5#diff-e6fdee794b5877d149cc44c8a5e9d146
